---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(tidybayes)
library(rjags)
library(here)
```

Read in model results
```{r}
m_results <- readRDS(here("modeling", "extinction_models", "results", "dynocc_full.rds"))
```

Prep data for plotting
```{r}
# m_results$sims.list$lpy_forecast[,,1] %>% View()
# dim(m_results$sims.list$lpy_forecast)
# m_results$sims.list$lpy_forecast

forecasts <- map(1:6, function(x){
  y <- m_results$sims.list$lpy_forecast[,,x]
  colnames(y) <- 1:16
  z <- y %>% 
    as_tibble(.name_repair = "minimal") %>% 
    mutate(forecast = x)
  
  z$chain <- 1:nrow(z)
  
  return(z)
}) %>% 
  bind_rows() %>% 
  pivot_longer(cols = as.character(1:16),
               names_to = "year",
               values_to = "lek_count") %>% 
  mutate(forecast = factor(forecast, levels = 1:6, labels = c("No change", "20% decline", "50% decline", "20% increase", "50% increase", "No CRP")),
         year = as.numeric(year))
```

Extract estimated pct change over the timeframe
```{r}
pct_change <- map(unique(forecasts$forecast), function(x){
  initial <- forecasts %>% 
    filter(forecast == x, year == 1) %>% 
    pull(lek_count)
  
  final <- forecasts %>% 
    filter(forecast == x, year == 16) %>% 
    pull(lek_count)
  
  tibble(change = (final - initial)/initial,
         forecast = x)
}) %>% 
  bind_rows()

pct_change <- pct_change %>% 
  group_by(forecast) %>% 
  summarise(median = median(change), lcl = quantile(change, 0.025), hcl = quantile(change, 0.975)) %>% 
  mutate(median = round(median, 2),
         lcl = round(lcl, 2),
         hcl = round(hcl, 2)) %>% 
  mutate(label = paste0(median*100, "% [", lcl*100, "%, ", hcl*100, "%]"))
```

Subsample to 10 trajectories for graphing
```{r}
set.seed(8)
chains_to_display <- sample(1:max(forecasts$chain), 10)

forecasts_small <- forecasts %>% 
  filter(chain %in% chains_to_display) %>% 
  mutate(chain = as.factor(chain))
```

Plot and save
```{r}
ann_text <- tibble(x = c(7.5, 7.5, 7.5, 7.5, 7.5, 7.5),
                   y = c(10, 10, 10, 10, 10, 10),
                   label = pct_change$label,
                   forecast = pct_change$forecast)

forecasts_small %>% 
  mutate(forecast = factor(forecast, levels = rev(c("No CRP", "50% decline", "20% decline", "No change", "20% increase", "50% increase")))) %>% 
  ggplot(aes(x = year - 1, y = lek_count)) +
  stat_lineribbon(data = forecasts, .width = c(.95, .8, .5), alpha = 0.5, point_interval = median_qi) +
  geom_line(aes(group = chain, color = chain), alpha = 0.25, linetype = "solid") +
  scale_fill_manual(values = rev(c("#636363", "#bdbdbd", "#f0f0f0"))) +
  facet_wrap(vars(`forecast`)) + 
  theme_bw() +
  geom_text(data = ann_text, aes(x = x, y = y, label = label)) +
  labs(x = "Years after 2021", y = "Number of leks in surveyed areas", fill = "CRI") +
  scale_color_discrete() +
  scale_y_continuous(breaks = seq(10,110,20)) + #
  coord_cartesian(ylim = c(5, 80)) +
  guides(color = "none")

ggsave(here("modeling", "extinction_models", "forecasts", "forecast_lek_count.png"), width = 8/1.2, height = 6/1.2, units = "in")
```

